<a href="https://colab.research.google.com/github/VanshishChaturvedi/Internship-tbi/blob/main/Practice_task_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Problem Statement:**

A data engineer at a fintech startup has received a raw employee payroll DataFrame containing several data quality issues. The task is to write a complete pandas cleaning pipeline that handles missing values, junk characters in the salary column, inconsistent capitalization in the department column, and date parsing — following the strategies for each column type. The cleaned DataFrame must have no remaining null values, correct dtypes, and pass a validation check.
 <br>
 <br>
Constraints & Requirements:
 <br>
Use only pandas and NumPy (import as pd and np)<br>
For categorical string columns with missing values, fill with 'unknown'<br><br>
For numeric columns with missing values, fill with the column's median computed using np.median() on the non-null values<br><br>
For the salary column: remove the ₹ symbol and commas using str.replace(regex=False), then convert to numeric using pd.to_numeric(errors='coerce'), then fill remaining NaN with the median<br><br>
For the date column: use pd.to_datetime(errors='coerce', dayfirst=True) and fill NaT with pd.to_datetime('1900-01-01')<br><br>
For text columns: apply astype(str).str.strip().str.title() to standardize capitalization<br><br>
After filling the age column's NaN, cast it to int using astype(int)<br><br>
Assemble a clean_df from the individually cleaned columns<br><br>
Validate by printing clean_df.isnull().sum() and calling clean_df.info()<br><br>
Inlined Sample Data & Inputs (required if Q11 references data, files, schemas, logs, or API payloads):
 <br><br>
Use the following 8-row employee dataset. Define it exactly as shown in your solution:
 <br><br>
import pandas as pd<br>
import numpy as np
 <br><br>
data = {<br>
    **'employee_id'**: [1, 2, 3, 4, 5, 6, 7, 8],<br><br>
    **'name'**:        ['Alice', 'Bob', 'Carol', 'Dave', 'Eve', 'Frank', 'Grace', 'Hank'],<br><br>
    **'department'**:  ['HR', 'it', None, ' Finance ', 'IT', None, 'hr', 'Finance'],<br><br>
    **'age'**:         [25.0, 32.0, None, 28.0, 30.0, None, 27.0, 35.0],<br><br>
    **'salary'**:      ['₹45,000', '₹60,000', None, '₹1,20,000', '₹50,000', 'Not Available', '₹55,000', '₹70,000'],<br><br>
    **'joining_date'**:['2022-01-15', '15/03/2021', 'invalid date', '2020-07-01', '10/08/2019', None, '2023-05-20', '2021-11-30'],<br><br>
    **'city'**:        ['Mumbai', None, 'Delhi', 'Bangalore', None, 'Chennai', 'Pune', 'Hyderabad']<br>
}
 <br><br>
df = pd.DataFrame(data)
Expected output for the inlined sample:
 <br><br>
After running your complete cleaning pipeline, clean_df.isnull().sum() must print all zeros:
 <br>
``` employee_id      0 ```<br>
``` name             0 ```<br>
``` department       0 ```<br>
``` age              0 ```<br>
``` alary           0 ```<br>
``` joining_date     0 ```<br>
``` city             0 ```<br>
``` dtype: int64 ```<br>
 <br>
The department column values must be title-cased and stripped (e.g., ' Finance ' → 'Finance', 'it' → 'It', None rows → 'Unknown').
 <br>
The age column must be integer dtype with NaN entries filled with median age (29).
 <br>
The salary column must be numeric float64 with NaN/unconvertible entries filled with median salary (57500.0).
 <br>
 <br>
Submission Format:
 <br>
Paste your complete answer (including code, if applicable) into the text box on the platform, following the structure shown in the Submission Format Example below.

# **Solution:**

In [43]:
import numpy as np
import pandas as pd

In [44]:
data = {
    'employee_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'name':        ['Alice', 'Bob', 'Carol', 'Dave', 'Eve', 'Frank', 'Grace', 'Hank'],
    'department':  ['HR', 'it', None, ' Finance ', 'IT', None, 'hr', 'Finance'],
    'age':         [25.0, 32.0, None, 28.0, 30.0, None, 27.0, 35.0],
    'salary':      ['₹45,000', '₹60,000', None, '₹1,20,000', '₹50,000', 'Not Available', '₹55,000', '₹70,000'],
    'joining_date':['2022-01-15', '15/03/2021', 'invalid date', '2020-07-01', '10/08/2019', None, '2023-05-20', '2021-11-30'],
    'city':        ['Mumbai', None, 'Delhi', 'Bangalore', None, 'Chennai', 'Pune', 'Hyderabad']
}

df = pd.DataFrame(data)

In [45]:
df

   employee_id   name department   age         salary  joining_date       city
0            1  Alice         HR  25.0        ₹45,000    2022-01-15     Mumbai
1            2    Bob         it  32.0        ₹60,000    15/03/2021       None
2            3  Carol       None   NaN           None  invalid date      Delhi
3            4   Dave   Finance   28.0      ₹1,20,000    2020-07-01  Bangalore
4            5    Eve         IT  30.0        ₹50,000    10/08/2019       None
5            6  Frank       None   NaN  Not Available          None    Chennai
6            7  Grace         hr  27.0        ₹55,000    2023-05-20       Pune
7            8   Hank    Finance  35.0        ₹70,000    2021-11-30  Hyderabad

In [46]:
df.isna().sum()

employee_id     0
name            0
department      2
age             2
salary          1
joining_date    1
city            2
dtype: int64

In [47]:
df['department'] = df['department'].fillna('Unknown')
df['department'] = df['department'].astype(str).str.strip().str.title()
df

   employee_id   name department   age         salary  joining_date       city
0            1  Alice         Hr  25.0        ₹45,000    2022-01-15     Mumbai
1            2    Bob         It  32.0        ₹60,000    15/03/2021       None
2            3  Carol    Unknown   NaN           None  invalid date      Delhi
3            4   Dave    Finance  28.0      ₹1,20,000    2020-07-01  Bangalore
4            5    Eve         It  30.0        ₹50,000    10/08/2019       None
5            6  Frank    Unknown   NaN  Not Available          None    Chennai
6            7  Grace         Hr  27.0        ₹55,000    2023-05-20       Pune
7            8   Hank    Finance  35.0        ₹70,000    2021-11-30  Hyderabad

In [48]:
df['salary'] = df['salary'].astype(str).str.replace('₹', '', regex=False).str.replace(',', '', regex=False)
df['salary'] = pd.to_numeric(df['salary'], errors='coerce')
df['salary'] = df['salary'].fillna(np.median(df['salary'].dropna()))
df

   employee_id   name department   age    salary  joining_date       city
0            1  Alice         Hr  25.0   45000.0    2022-01-15     Mumbai
1            2    Bob         It  32.0   60000.0    15/03/2021       None
2            3  Carol    Unknown   NaN   57500.0  invalid date      Delhi
3            4   Dave    Finance  28.0  120000.0    2020-07-01  Bangalore
4            5    Eve         It  30.0   50000.0    10/08/2019       None
5            6  Frank    Unknown   NaN   57500.0          None    Chennai
6            7  Grace         Hr  27.0   55000.0    2023-05-20       Pune
7            8   Hank    Finance  35.0   70000.0    2021-11-30  Hyderabad

In [49]:
df['joining_date'] = df['joining_date'].astype(str).str.replace('/', '-', regex=False)
df['joining_date'] = pd.to_datetime(df['joining_date'], errors='coerce', dayfirst=True, format='mixed')
df['joining_date'] = df['joining_date'].fillna(pd.to_datetime('1900-01-01'))
df

   employee_id   name department   age    salary joining_date       city
0            1  Alice         Hr  25.0   45000.0   2022-01-15     Mumbai
1            2    Bob         It  32.0   60000.0   2021-03-15       None
2            3  Carol    Unknown   NaN   57500.0   1900-01-01      Delhi
3            4   Dave    Finance  28.0  120000.0   2020-07-01  Bangalore
4            5    Eve         It  30.0   50000.0   2019-08-10       None
5            6  Frank    Unknown   NaN   57500.0   1900-01-01    Chennai
6            7  Grace         Hr  27.0   55000.0   2023-05-20       Pune
7            8   Hank    Finance  35.0   70000.0   2021-11-30  Hyderabad

In [50]:
df['age'] = df['age'].astype(float)
df['age'] = df['age'].fillna(df['age'].median())
df['age'] = df['age'].astype(int)
df

   employee_id   name department  age    salary joining_date       city
0            1  Alice         Hr   25   45000.0   2022-01-15     Mumbai
1            2    Bob         It   32   60000.0   2021-03-15       None
2            3  Carol    Unknown   29   57500.0   1900-01-01      Delhi
3            4   Dave    Finance   28  120000.0   2020-07-01  Bangalore
4            5    Eve         It   30   50000.0   2019-08-10       None
5            6  Frank    Unknown   29   57500.0   1900-01-01    Chennai
6            7  Grace         Hr   27   55000.0   2023-05-20       Pune
7            8   Hank    Finance   35   70000.0   2021-11-30  Hyderabad

In [51]:
df = df.fillna("Unkonwn")
df

   employee_id   name department  age    salary joining_date       city
0            1  Alice         Hr   25   45000.0   2022-01-15     Mumbai
1            2    Bob         It   32   60000.0   2021-03-15    Unkonwn
2            3  Carol    Unknown   29   57500.0   1900-01-01      Delhi
3            4   Dave    Finance   28  120000.0   2020-07-01  Bangalore
4            5    Eve         It   30   50000.0   2019-08-10    Unkonwn
5            6  Frank    Unknown   29   57500.0   1900-01-01    Chennai
6            7  Grace         Hr   27   55000.0   2023-05-20       Pune
7            8   Hank    Finance   35   70000.0   2021-11-30  Hyderabad

In [52]:
df.isnull().sum()

employee_id     0
name            0
department      0
age             0
salary          0
joining_date    0
city            0
dtype: int64

1 block solution:
import numpy as np
import pandas as pd
data = {
    'employee_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'name':        ['Alice', 'Bob', 'Carol', 'Dave', 'Eve', 'Frank', 'Grace', 'Hank'],
    'department':  ['HR', 'it', None, ' Finance ', 'IT', None, 'hr', 'Finance'],
    'age':         [25.0, 32.0, None, 28.0, 30.0, None, 27.0, 35.0],
    'salary':      ['₹45,000', '₹60,000', None, '₹1,20,000', '₹50,000', 'Not Available', '₹55,000', '₹70,000'],
    'joining_date':['2022-01-15', '15/03/2021', 'invalid date', '2020-07-01', '10/08/2019', None, '2023-05-20', '2021-11-30'],
    'city':        ['Mumbai', None, 'Delhi', 'Bangalore', None, 'Chennai', 'Pune', 'Hyderabad']
}

df = pd.DataFrame(data)
df['department'] = df['department'].fillna('Unknown')
df['department'] = df['department'].astype(str).str.strip().str.title()
df['salary'] = df['salary'].astype(str).str.replace('₹', '', regex=False).str.replace(',', '', regex=False)
df['salary'] = pd.to_numeric(df['salary'], errors='coerce')
df['salary'] = df['salary'].fillna(np.median(df['salary'].dropna()))
df['joining_date'] = df['joining_date'].astype(str).str.replace('/', '-', regex=False)
df['joining_date'] = pd.to_datetime(df['joining_date'], errors='coerce', dayfirst=True, format='mixed')
df['joining_date'] = df['joining_date'].fillna(pd.to_datetime('1900-01-01'))
df['age'] = df['age'].astype(float)
df['age'] = df['age'].fillna(df['age'].median())
df['age'] = df['age'].astype(int)
df = df.fillna("Unkonwn")
df