<a href="https://colab.research.google.com/github/VanshishChaturvedi/Internship-tbi/blob/main/Practice_task_9/Practice_task_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Problem Statement**
You are given a sales dataset for a retail chain. Your task is to use Pandas groupby and aggregation to produce a region-level and category-level summary.

**Dataset** <br>
Create the following DataFrame in your notebook:
 ``` python
import pandas as pd

data = {
    'sale_id':   [1, 2, 3, 4, 5, 6, 7, 8],
    'region':    ['North', 'South', 'North', 'East', 'South', 'East', 'North', 'South'],
    'category':  ['Electronics', 'Clothing', 'Clothing', 'Electronics', 'Electronics', 'Clothing', 'Electronics', 'Clothing'],
    'amount':    [1500, 800, 600, 2200, 950, 700, 1800, 450]
}
df = pd.DataFrame(data)
 ```

**Tasks:**<br>
Compute total sales per region: Group by region, compute the sum of amount, reset the index, and rename the amount column to total_sales.<br><br>
Compute average sales per category: Group by category, compute the mean of amount, reset the index, and rename the amount column to avg_sales.<br><br>
Multi-column grouping: Group by both region and category simultaneously, compute the total amount using .agg(), reset the index, and rename the aggregated column to regional_category_total.<br><br>
Print all three resulting DataFrames.

In [9]:
import pandas as pd

data = {
    'sale_id':   [1, 2, 3, 4, 5, 6, 7, 8],
    'region':    ['North', 'South', 'North', 'East', 'South', 'East', 'North', 'South'],
    'category':  ['Electronics', 'Clothing', 'Clothing', 'Electronics', 'Electronics', 'Clothing', 'Electronics', 'Clothing'],
    'amount':    [1500, 800, 600, 2200, 950, 700, 1800, 450]
}
df = pd.DataFrame(data)

In [10]:
df

   sale_id region     category  amount
0        1  North  Electronics    1500
1        2  South     Clothing     800
2        3  North     Clothing     600
3        4   East  Electronics    2200
4        5  South  Electronics     950
5        6   East     Clothing     700
6        7  North  Electronics    1800
7        8  South     Clothing     450

In [11]:
df.groupby('region').agg(total_sales=('amount','sum')).reset_index()

  region  total_sales
0   East         2900
1  North         3900
2  South         2200

In [12]:
df.groupby('category').agg(avg_sales=('amount','mean')).reset_index()

      category  avg_sales
0     Clothing      637.5
1  Electronics     1612.5

In [13]:
df.groupby(['region', 'category']).agg(regional_category_total=('amount','sum')).reset_index()

  region     category  regional_category_total
0   East     Clothing                      700
1   East  Electronics                     2200
2  North     Clothing                      600
3  North  Electronics                     3300
4  South     Clothing                     1250
5  South  Electronics                      950

## One Block Solution

``` python
import pandas as pd

data = {
    'sale_id':   [1, 2, 3, 4, 5, 6, 7, 8],
    'region':    ['North', 'South', 'North', 'East', 'South', 'East', 'North', 'South'],
    'category':  ['Electronics', 'Clothing', 'Clothing', 'Electronics', 'Electronics', 'Clothing', 'Electronics', 'Clothing'],
    'amount':    [1500, 800, 600, 2200, 950, 700, 1800, 450]
}
df = pd.DataFrame(data)
df.groupby('region').agg(total_sales=('amount','sum')).reset_index()
df.groupby('category').agg(avg_sales=('amount','mean')).reset_index()
df.groupby(['region', 'category']).agg(regional_category_total=('amount','sum')).reset_index()
```